### PR TITLE
Fail feature macro compare if compiler has more features than runtime

### LINKED ISSUE #979: Test compiler features macro need to be fixed in some areas
Add fixes for the following comments:
https://github.com/KhronosGroup/OpenCL-CTS/pull/762
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494445361
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494445638
https://github.com/KhronosGroup/OpenCL-CTS/pull/762#discussion_r494468614

### PR DESCRIPTION
**Pull request by alycm**
Because a C++11 `std::equal` only iterates over the first container, and
matches with items in the second, if the second container contains more items
the check can still pass even though they're not identical.  Just use `==`
instead.

Fixes #979

### CODE REVIEW

File: test_conformance/compiler/test_feature_macro.cpp [hunk 1]
```diff
@@ -686,9 +686,7 @@ int test_consistency_c_features_list(cl_device_id deviceID,
     sort(vec_to_cmp.begin(), vec_to_cmp.end());
     sort(vec_device_feature_names.begin(), vec_device_feature_names.end());
 
-    cl_bool result =
-        std::equal(vec_device_feature_names.begin(),
-                   vec_device_feature_names.end(), vec_to_cmp.begin());
+    cl_bool result = vec_device_feature_names == vec_to_cmp;
     if (result)
```
Comment (bashbaug) [inline test_conformance/compiler/test_feature_macro.cpp:690]: I'm not going to lose sleep over this, but I'd find this check easier to understand without the extra boolean variable (and `operator==` doesn't return a `cl_bool` anyhow).

**Review by bashbaug — COMMENTED** [review]
LGTM - probably should wait for any comments from @gwawiork before merging though.

File: test_conformance/compiler/test_feature_macro.cpp (hunk 1 above)
Comment (alycm) [reply test_conformance/compiler/test_feature_macro.cpp]: Good point, I've changed it.

**Comment by lakshmih** [comment]
Qualcomm tested the compiler feature_macros sub_test with this change and it passed.

**Review by gwawiork — APPROVED** [review]
LGTM

**Review by Jeremy-Kemp — APPROVED** [review]
LGTM!
