### PR TITLE
Test SVM: Fix - do not use unmapped pointer.

### LINKED ISSUE #660: Test SVM: pointer_passing - passing unmapped pointer to clSetKernelArgSVMPointer is incorrect
See 
Unmapping: https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_pointer_passing.cpp#L76

Usage:
https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/SVM/test_pointer_passing.cpp#L84

There should be assigned pbuf not pBuf to pChar.

### PR DESCRIPTION
**Pull request by gwawiork**
Fixes #660

### CODE REVIEW

File: test_conformance/SVM/test_pointer_passing.cpp [hunk 1]
```diff
@@ -50,7 +50,7 @@ int test_svm_pointer_passing(cl_device_id deviceID, cl_context context2, cl_comm
   test_error(error,"clCreateKernel failed");
 
   size_t bufSize = 256;
-  char *pbuf = (char*) clSVMAlloc(context, CL_MEM_READ_WRITE, sizeof(cl_uchar)*bufSize, 0);
+  cl_uchar *pbuf = (cl_uchar*) clSVMAlloc(context, CL_MEM_READ_WRITE, sizeof(cl_uchar)*bufSize, 0);
```
Comment (Jeremy-Kemp) [inline test_conformance/SVM/test_pointer_passing.cpp]: Could we just rename this entirely? Its very confusing and easy to make a mistake having both `pbuf` and `pBuf`.
