### PR TITLE
Fix conversion fail when build with -O2 fail

### LINKED ISSUE #1146: clz got incorrect value when compile CTS with -O2
clz that in test_conformance/conversion/fplib.cpp  got incorrect value when compile with -O2  on arm64 , this casue test_conversion -w float_rtz_long fail.
```
     649) Testing convert_floatn_rtz( longn ):
     Building convert_float_rtz( long ) test
     Building convert_float2_rtz( long2 ) test
     Building convert_float3_rtz( long3 ) test
     Building convert_float4_rtz( long4 ) test
     Building convert_float8_rtz( long8 ) test
     Building convert_float16_rtz( long16 ) test
     Testing... .
     Error for vector size 1 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     
     Error for vector size 2 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     
     Error for vector size 3 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     
     Error for vector size 4 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     
     Error for vector size 8 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     
     Error for vector size 16 found at 0x0000003f:  *-0x1p-1 vs -0x1p+63
     Input value: 0x8000000000000000  (convert_float_rtz( long ))
     	 *** 649) convert_floatn_rtz( longn ) FAILED ** 
```

my test:
```
~# cat t.c
#include <stdint.h>
#include <stdio.h>

#if !defined(FLT_MANT_DIG)
#define FLT_MANT_DIG    24
#endif
#define as_float(x)     (*((float *)(&x)))
#define as_long(x)      (*((int64_t *)(&x)))

static uint32_t clz(uint64_t value)
{
    uint32_t num_zeros;

    for( num_zeros = 0; num_zeros < (sizeof(uint64_t)*8); num_zeros++)
    {
        uint64_t v = 0x8000000000000000ull & (value << num_zeros);

        if( 0 != (0x8000000000000000 & (value << num_zeros)) ) /* <==  if( 0 != ( ((uint64_t)(0x8000000000000000ull)) & (uint64_t)(value << num_zeros)) )  can pass */
            break;
    }
    return num_zeros;
}

float qcom_s64_2_f32(int64_t data)
{
        int sign = 0;
        if (!data)
                return 0.0f;
        if (data < 0){
                data = -data;
                sign = 1;
        }

        uint32_t    exponent   = (127 + 64 - clz(data) - 1) << (FLT_MANT_DIG - 1); //add 1 for the implied 1.0 in normalized fp32 numbers
        int         mantShift  = 40 - clz(data);
        uint32_t    mantissa;

        printf("e:%d   s:%d    clz:%d data:%llx sign:%d \n", exponent, mantShift, clz(data), data, sign);

        if (mantShift >= 0)
                mantissa = (uint32_t)(((uint64_t)data) >> mantShift);
        else
                mantissa = (uint32_t)(((uint64_t)data) << -mantShift);
        mantissa &= 0x7fffff;//mask off the leading 1

        uint32_t result = exponent | mantissa;
        if (sign)
                result |= 0x80000000;
        return as_float(result);
}

int main(int argc, char **argv)
{
        int64_t l = 0x8000000000000000ll;
        float f = l;

        printf("f = %a\n", f);

        float f2 = qcom_s64_2_f32(l);

        printf("f2=%a\n", f2);
        return 0;
}
~# gcc t.c
~# ./a.out
f = -0x1p+63
e:1593835520   s:40    clz:0 data:8000000000000000 sign:1
f2=-0x1p+63
~# gcc -O2 t.c
~# ./a.out
f = -0x1p+63
e:1056964608   s:-24    clz:64 data:8000000000000000 sign:1
f2=-0x1p-1
~#
~# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-poky-linux/9.2.0/lto-wrapper
Target: aarch64-poky-linux
Configured with: ../../../../../../work-shared/gcc-9.2.0-r0/gcc-9.2.0/configure --build=x86_64-linux --host=aarch64-poky-linux --target=aarch64-poky-linux --prefix=/usr --exec_prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdt
Thread model: posix
gcc version 9.2.0 (GCC)
~#
```
TDM-GCC 9.2.0 got same result.
```

C:\>gcc t.c

C:\>a.exe
f = -0x1.000000p+63
e:1593835520   s:40    clz:0 data:8000000000000000 sign:1
f2=-0x1.000000p+63

C:\>gcc -O2 t.c

C:\>a.exe
f = -0x1.000000p+63
e:1056964608   s:-24    clz:64 data:8000000000000000 sign:1
f2=-0x1.000000p-1

C:\>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-git-9.2.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --enable-large-address-aware --disable-rpath --disable-symvers --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 9.2.0 (tdm64-1)

C:\>
```

### PR DESCRIPTION
**Pull request by ijkmn**
fix #1146

### CODE REVIEW

File: test_conformance/conversions/fplib.cpp [hunk 1]
```diff
@@ -29,8 +29,8 @@ static uint32_t clz(uint64_t value)
 
     for( num_zeros = 0; num_zeros < (sizeof(uint64_t)*8); num_zeros++)
     {
-        if(0x8000000000000000 & (value << num_zeros))
-            break;
+        volatile uint64_t v = 0x8000000000000000ull & (value << num_zeros);
```
Comment (jlewis-austin) [inline test_conformance/conversions/fplib.cpp:32]: Were both the volatile and the "ull" required to fix this? Looking back at the issue, I don't think my previous explanation of undefined behavior on integer overflow makes sense since conversions to unsigned should be well-defined. 
The change looks fine to me--I'm just trying to understand if the code was incorrect or if it's a compiler bug workaround.

**Review by jlewis-austin — APPROVED** [review]

**Review by yzhang-verisilicon — APPROVED** [review]

File: test_conformance/conversions/fplib.cpp (hunk 1 above)
Comment (ijkmn) [reply test_conformance/conversions/fplib.cpp:32]: i think it should be gcc 9.2 compiler bug, i tested with gcc 5.1, it's ok.
```
C:\conversion>gcc t.c

C:\conversion>a.exe
f = -0x1.000000p+63
e:1593835520   s:40    clz:0 data:8000000000000000 sign:1
f2=-0x1.000000p+63

C:\conversion>gcc -O2 t.c

C:\conversion>a.exe
f = -0x1.000000p+63
e:1593835520   s:40    clz:0 data:8000000000000000 sign:1
f2=-0x1.000000p+63

C:\conversion>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/tdm/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

C:\conversion>
```

**Comment by callumfare** [comment]
This fixes a failure I was also seeing in test_conversion float_rtz_long. I'm also using GCC 9.2. The `volatile` keyword seems to be a necessary part of the change so it seems like there's a compiler bug that this works around

**Review by EwanC — APPROVED** [review]
