### PR TITLE
Fix clang 10 build errors

### LINKED ISSUE #855: Implicit conversion from int to float changes value of CL_INT_MAX
I am getting the following errors when compiling the current master branch using clang 10.0.0:

```
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-CTS/test_common/harness/imageHelpers.cpp:2731:150: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
                ptr[ i ] = (int)CONVERT_INT( srcVector[ i ], MAKE_HEX_FLOAT( -0x1.0p31f, -1, 31), MAKE_HEX_FLOAT( 0x1.fffffep30f, 0x1fffffe, 30-23), CL_INT_MAX  );
                         ~                                                                                                                           ^~~~~~~~~~
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-Headers/CL/cl_platform.h:250:29: note: expanded from macro 'CL_INT_MAX'
#define CL_INT_MAX          2147483647
                            ^~~~~~~~~~
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-CTS/test_common/harness/imageHelpers.h:68:75: note: expanded from macro 'CONVERT_INT'
#define CONVERT_INT( v, min, max, max_val)  ( v < min ? min : ( v > max ? max_val : round_to_even( v ) ) )
                                                                          ^~~~~~~
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-CTS/test_common/harness/imageHelpers.cpp:2890:188: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
                errors[i] = (cl_float)((cl_long) ptr[ i ] - (cl_long) CONVERT_INT( srcVector[ i ], MAKE_HEX_FLOAT( -0x1.0p31f, -1, 31), MAKE_HEX_FLOAT( 0x1.fffffep30f, 0x1fffffe, 30-23), CL_INT_MAX  ));
                                                          ~                                                                                                                                ^~~~~~~~~~
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-Headers/CL/cl_platform.h:250:29: note: expanded from macro 'CL_INT_MAX'
#define CL_INT_MAX          2147483647
                            ^~~~~~~~~~
/home/pmoreau/Projects/OpenCL_for_Nouveau/src/OpenCL-CTS/test_common/harness/imageHelpers.h:68:75: note: expanded from macro 'CONVERT_INT'
#define CONVERT_INT( v, min, max, max_val)  ( v < min ? min : ( v > max ? max_val : round_to_even( v ) ) )
```

### LINKED ISSUE #1250: Image Helpers: implicit conversion from 'int' to 'float' changes value
Clang 12 (and possibly some older versions as well) report issues such as:

https://github.com/KhronosGroup/OpenCL-CTS/blob/657283799482433cc35d119ddab220dcad1f00aa/test_common/harness/imageHelpers.cpp#L2724-L2727

imageHelpers.cpp:2727:21: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]

Another occurence:

https://github.com/KhronosGroup/OpenCL-CTS/blob/657283799482433cc35d119ddab220dcad1f00aa/test_common/harness/imageHelpers.cpp#L2893-L2896

### PR DESCRIPTION
**Pull request by jlewis-austin**
Lossy casts due to inexact float representation of CL_INT_MAX
Fixes #1250
Fixed #855

### CODE REVIEW

File: test_common/harness/imageHelpers.cpp [hunk 1]
```diff
@@ -2765,10 +2765,7 @@ void pack_image_pixel(float *srcVector, const cl_image_format *imageFormat,
         case CL_SIGNED_INT32: {
             cl_int *ptr = (cl_int *)outData;
             for (unsigned int i = 0; i < channelCount; i++)
-                ptr[i] = (int)CONVERT_INT(
-                    srcVector[i], MAKE_HEX_FLOAT(-0x1.0p31f, -1, 31),
-                    MAKE_HEX_FLOAT(0x1.fffffep30f, 0x1fffffe, 30 - 23),
-                    CL_INT_MAX);
+                ptr[i] = round_to_even(srcVector[i]);
```
Comment (jlewis-austin) [inline test_common/harness/imageHelpers.cpp:2768]: Since round_to_even has clamping logic inside it, it works as intended for 32 bit types. The rest of the cases are basically hacks to correct the clamping behavior for different types. A long-term solution would be to templatize round_to_even to work correctly with all types.

**Comment by pierremoreau** [comment]
Thank you for the PR!
Feel free to also mention #855 being fixed by it in the description, so that issue also gets closed when this is merged.

**Comment by jlewis-austin** [comment]
> Thank you for the PR! Feel free to also mention #855 being fixed by it in the description, so that issue also gets closed when this is merged.

Done

> `add_cxx_flag_if_supported(-Wno-error=implicit-const-int-float-conversion)` could be removed as a result ([in here](https://github.com/KhronosGroup/OpenCL-CTS/blob/60471a520804fbd6611acd1c48f35549bb512deb/CMakeLists.txt#L97)). I tested locally with clang 13.0.0 that it compiles fine with your changes and without that flag.

Done, tested with clang 10 on linux

File: test_common/harness/imageHelpers.cpp (hunk 1 above)
Comment (kpet) [reply test_common/harness/imageHelpers.cpp:2768]: It might be good to create an issue so we don't forget to revisit this.

**Review by kpet — APPROVED** [review]

File: test_common/harness/imageHelpers.cpp (hunk 1 above)
Comment (jlewis-austin) [reply test_common/harness/imageHelpers.cpp:2768]: Done #1395

Comment (kpet) [reply test_common/harness/imageHelpers.cpp:2768]: Thanks!

**Comment by lakshmih** [comment]
Qualcomm tested this patch. No issues were seen.
