### PR TITLE
api tests fix: Free MTdata object in test_get_image_info

### LINKED ISSUE #1870: Memory leak in api tests
Valgrind output generated by calling: 

`valgrind  --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=./api/valgrind-log-file.txt ./api/test_api`

reports the following memory leak:
image

### PR DESCRIPTION
**Pull request by imilenkovic00**
Add call of free_mtdata function in test_get_image_info. This fixes memory leak in api tests.

Fixes #1870.

### CODE REVIEW

File: test_conformance/api/test_mem_object_info.cpp [hunk 1]
```diff
@@ -720,6 +720,8 @@ int test_get_image_info( cl_device_id deviceID, cl_context context, cl_mem_objec
         clReleaseMemObject( imageObject );
     }
 
+    free_mtdata(d);
```
Comment (svenvh) [inline test_conformance/api/test_mem_object_info.cpp:723]: An even better solution would be to replace the declaration/initialization of `MTdata d` by `MTdataHolder`, so that no manual `free_mtdata` calls are needed.  That would also fix the leaks on error paths.

Comment (imilenkovic00) [reply test_conformance/api/test_mem_object_info.cpp]: Thank you for your suggestion. Modified accordingly.

**Review by svenvh — APPROVED** [review]

**Comment by bashbaug** [comment]
Merging as discussed in the January 30th teleconference.
